- app/models/user.rb
> validation username remove

- app/assets/stylesheets/components/_uikit.scss
- app/views/pages/uikit.html
Uikit done with new color code
Tabs finished and functionnal
> Uikitfinal

- app/controllers/pages_controller.rb
- app/controllers/participations_controller.rb
- app/models/participation.rb
- app/views/gamenights/index.html.erb
- app/views/gamenights/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/participations/edit.html.erb
- config/routes.rb
> Participations

- app/assets/stylesheets/components/_uikit.scss
- app/views/pages/uikit.html
Pop up sur les tags pour games et locations
> uikit finished

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/boardgames/_form.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/gamenights/_form.html.erb
- app/views/locations/_form.html.erb
- app/views/participations/edit.html.erb
> forms done

- app/controllers/gamenights_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/participations_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/gamenights/index.html.erb
- app/views/gamenights/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/profil.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
> Dashboard update 2

- app/javascript/plugins/init_mapbox.js
- app/views/gamenights/index.html.erb
- db/schema.rb
- ajout search bar map
- changement style de la map 
- agrandissement de la map
Pas d'erreurs en localhost.
> style map ok

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/plugins/init_mapbox.js
- app/views/gamenights/index.html.erb
- footer fixed
- markers map designé 
- map sur le côté des card dans l'index
> front change

- app/javascript/packs/application.js
- app/javascript/plugins/init_star_rating.js
- app/views/layouts/application.html.erb
- app/views/pages/profil.html.erb
- app/views/participations/edit.html.erb
- db/schema.rb
- package.json
- yarn.lock
> Profile reviews

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_uikit.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/dashboard.html.erb
- db/schema.rb
css done on dashboard and form for edit user not fixed....
> Formeditusercss

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_uikit.scss
- app/controllers/application_controller.rb
- app/views/pages/dashboard.html.erb
Tab active fixed on dashboard
Edit user profil fixed
Buttons on forms changed
> Bugdashboard

- app/controllers/participations_controller.rb
- app/models/user.rb
- app/views/gamenights/show.html.erb
- app/views/pages/profil.html.erb
- app/views/participations/edit.html.erb
> Form rating

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Fixhomepagefront

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- contenu body homepage
- modifs css pour formulaires
> bodyhomepage

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_gamenightshow.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_uikit.scss
- app/views/gamenights/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
> Csshomedebug

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_profil-page.scss
- app/controllers/pages_controller.rb
- app/javascript/plugins/init_select2.js
- app/views/pages/profil.html.erb
- app/views/participations/edit.html.erb
> Profile texte

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_uikit.scss
- app/views/layouts/application.html.erb
LE FOOTER EST ENFIN STICKY EVERYWHEREEEEEEE
> FINITOPATATO

- app/assets/stylesheets/components/_gamenightshow.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/gamenights/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/profil.html.erb
- app/views/shared/_navbar.html.erb
> Show gamenight bb

- app/views/layouts/application.html.erb
> check done

- app/views/layouts/application.html.erb
> Debugfinal

- app/views/layouts/application.html.erb
> Favicon bb

- app/assets/stylesheets/components/_profil-page.scss
- app/views/pages/profil.html.erb
> Commentaires infos

- Gemfile
- Gemfile.lock
- app/controllers/gamenights_controller.rb
- app/views/gamenights/index.html.erb
- config/environment.rb
> gem not fixed

- app/controllers/gamenights_controller.rb
- app/models/user.rb
- app/views/gamenight_mailer/cancelation_notice.html.erb
- app/views/gamenight_mailer/cancelation_notice.text.erb
- app/views/user_mailer/welcome.html.erb
- app/views/user_mailer/welcome.text.erb
mailer disabled to check error
> Accountdebug

- app/controllers/gamenights_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/pages/profil.html.erb
- app/views/user_mailer/welcome.html.erb
- app/views/user_mailer/welcome.text.erb
- db/seeds.rb
> Pagination profil

- app/controllers/gamenights_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/contact_mailer.rb
- app/mailers/gamenight_mailer.rb
- app/views/gamenight_mailer/cancelation_notice.html.erb
- app/views/gamenight_mailer/cancelation_notice.text.erb
- app/views/pages/home.html.erb
- app/views/participation_mailer/cancelation_notice.html.erb
- app/views/user_mailer/welcome.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/smtp.rb
- test/mailers/gamenight_mailer_test.rb
- test/mailers/previews/gamenight_mailer_preview.rb
Mailing finished for cancelation gamenight & participation + new user
mailing operational for dev and prod with ludin.fun@gmail.com
> Mailerfinal

- app/controllers/gamenights_controller.rb
- app/javascript/plugins/init_mapbox.js
index gamenights : fusion des gamenights display + geocodées + filtrées
> Gamenights geocoded paginate

- app/controllers/pages_controller.rb
- app/views/locations/_form.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
compteur dashboard & autocomplete address
> Compteurs dashboard

- app/views/locations/_form.html.erb
- app/views/pages/home.html.erb
Algolia script modified for APIkey in .env
> Activity counter
